# For more info on HTTP files go to https://aka.ms/vs/httpfile
@GatewayAPI_HostAddress = https://localhost:7029

GET {{GatewayAPI_HostAddress}}/
Accept: application/json

###

GET {{GatewayAPI_HostAddress}}/PricingTasks
Accept: application/json

###

POST {{GatewayAPI_HostAddress}}/PricingTasks/bsPrice
Accept: application/json
Content-Type: application/json

{"timeSlices":10,"optionType":0,"spot":100.0,"strike":150.0,"rate":1.0,"carry":1.0,"vol":0.3}
###

POST {{ProjectX.GatewayAPI_HostAddress}}/pricingtasks/bsPrice
Content-Type: application/json

{
  //OptionsPricingByMaturitiesRequest
}
###