# For more info on HTTP files go to https://aka.ms/vs/httpfile
@GatewayAPI_HostAddress = https://localhost:8081

GET {{GatewayAPI_HostAddress}}/
Accept: application/json

###

GET {{GatewayAPI_HostAddress}}/PricingTasks
Accept: application/json

###

POST {{GatewayAPI_HostAddress}}/PricingTasks/bsPrice
Accept: application/json
Content-Type: application/json

{"timeSlices":10,"optionType":0,"spot":100.0,"strike":150.0,"rate":1.0,"carry":1.0,"vol":0.3,"CalculatorType":2}
###

POST {{GatewayAPI_HostAddress}}/PricingTasks/bsPlot
Content-Type: application/json

{
    "Id": "73ed11f2-9e2e-45ba-a479-f0a54b0a093e",
    "GreekType": 0,
    "OptionType": 0,
    "Strike": 30,
    "Rate": 0.6,
    "Carry": 0.5,
    "Vol": 0.3,
    "ZLabel": "z",
    "ZDecimalPlaces": 0,
    "ZTickDecimalPlaces": 0,
    "CalculatorType": 0
 }
###
GET {{GatewayAPI_HostAddress}}/BacktestService
Accept: application/json
###

GET {{GatewayAPI_HostAddress}}/BacktestService/LongShortStrategy?ticker=AAPL&fromDate=2023-05-01&toDate=2023-09-25&notional=10000
Accept: application/json
###

GET {{GatewayAPI_HostAddress}}/BacktestService/LongShortStrategy?ticker=IBM&fromDate=2023-05-01&toDate=2023-09-25&notional=10000
Accept: application/json
###

GET {{GatewayAPI_HostAddress}}/BacktestService/LongShortStrategy?ticker=BTCUSD&fromDate=2023-05-01&toDate=2023-09-25&notional=10000
Accept: application/json
###
GET {{GatewayAPI_HostAddress}}/BacktestService/LongShortStrategy?ticker=CCCC&fromDate=2023-05-01&toDate=2023-09-25&notional=10000
Accept: application/json
###

GET {{GatewayAPI_HostAddress}}/BacktestService/LongShortStrategy?ticker=STTK&fromDate=2023-05-01&toDate=2023-09-25&notional=10000
Accept: application/json
###

GET {{GatewayAPI_HostAddress}}/BacktestService/LongShortStrategy?ticker=CPLS&fromDate=2023-05-01&toDate=2023-09-25&notional=10000
Accept: application/json
###

GET {{GatewayAPI_HostAddress}}/BacktestService/LongShortStrategy?ticker=SBNY&fromDate=2023-05-01&toDate=2023-09-25&notional=10000
Accept: application/json
###

GET {{GatewayAPI_HostAddress}}/BacktestService/LongShortStrategy?ticker=PHUN&fromDate=2023-05-01&toDate=2023-09-25&notional=10000
Accept: application/json
###

GET {{GatewayAPI_HostAddress}}/BacktestService/LongShortStrategy?ticker=SOXS&fromDate=2023-05-01&toDate=2023-09-25&notional=10000
Accept: application/json
###

GET {{GatewayAPI_HostAddress}}/BacktestService/LongShortStrategy?ticker=INTC&fromDate=2023-05-01&toDate=2023-09-25&notional=10000
Accept: application/json
###

GET {{GatewayAPI_HostAddress}}/BacktestService/LongShortStrategy?ticker=IVP&fromDate=2023-05-01&toDate=2023-09-25&notional=10000
Accept: application/json
###